### ISSUE TITLE
Rename idpattern to patternId

### ISSUE THREAD

**Issue by otisg** [fbalicchia/logagent-input-filter-grok#2]
What does "idpattern: FOO" do?  That just creates an ID for the provided pattern?  In that case patternId would be better name than idpattern.

**Comment by fbalicchia** [comment]
Done,
Parser search patternId to load grok patter from loaded file. In aws file under ./patterns folder 
patterId S3_REQUEST_LINE corresponds to  '(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})'

With the last commit I've add 
* aws  
* bacula  
* bro  
* exim	
* rails

files with a few grok patters that at the moment are not included in node-grok
